[project]
name = "decomposed-dynamics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sai Koukuntla", email = "sai.koukunt@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.8",
    "jax[cuda13]>=0.10.0",
    "jaxopt>=0.8.5",
    "optax>=0.2.8",
    "tqdm>=4.67.3",
]

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
simulations = {workspace = true}

[tool.uv.workspace]
members = ["simulations"]

[dependency-groups]
dev = [
    "matplotlib>=3.10.9",
    "simulations",
    "tornado>=6.5.7",
]

